export default [
    'BA, Advertising',
    'BA, American Studies',
    'BA, Anthropology',
    'BA, Architecture',
    'BA, Art',
    'BA, Art History',
    'BA, Asian Studies',
    'BA, Business',
    'BA, Chinese',
    'BA, Communication',
    'BA, Computer Science',
    'BA, English',
    'BA, European Studies',
    'BA, French',
    'BA, German',
    'BA, Government',
    'BA, History',
    'BA, Humanities',
    'BA, International Business',
    'BA, Journalism',
    'BA, Latin American Studies',
    'BA, Linguistics',
    'BA, Management',
    'BA, Marketing',
    'BA, Mathematics',
    'BA, Music',
    'BA, Nursing',
    'BA, Philosophy',
    'BA, Photography',
    'BA, Physics',
    'BA, Political Science',
    'BA, Psychology',
    'BA, Public Relations',
    'BA, Sociology',
    'BA, Social Work',
    'BA, Theatre Studies',
    'BS, Accounting',
    'BS, Aerospace Engineering',
    'BS, Architectural Engineering',
    'BS, Astronomy',
    'BS, Biochemistry',
    'BS, Biology',
    'BS, Biomedical Engineering',
    'BS, Chemical Engineering',
    'BS, Chemistry',
    'BS, Civil Engineering',
    'BS, Computer Science',
    'BS, Economics',
    'BS, Electrical and Computer Engineering',
    'BS, Geological Sciences',
    'BS, Human Development and Family Services',
    'BS, Finance',
    'BS, Information and Computer Science',
    'BS, Kinesiology',
    'BS, Mathematics',
    'BS, Mechanical Engineering',
    'BS, Neuroscience',
    'BS, Petroleum Engineering',
    'BS, Physics',
    'BS, Pre-Pharmacy',
    'BS, Statistics',
    'BS, Supply Chain Management',
    'Certificate, Full Stack Web Development',
    'Certificate, Project Management Professional',
    'MA, Architecture',
    'MA, Educational Psychology',
    'MA, German',
    'MA, Psychology',
    'MA, Public Affairs',
    'MS, Accounting',
    'MS, Aerospace Engineering',
    'MS, Business Administration',
    'MS, Civil Engineering',
    'MS, Finance',
    'MS, Information Studies',
    'MS, Mathematics',
    'MS, Mechanical Engineering',
    'MS, Statistics',
    'PhD, Computer Science',
    'PhD, Mathematics',
];